// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxE6calGsvU3XX71hXBx6u7z3m8lYXnQ',
    appId: '1:395805938406:web:c857b677f63190696d2127',
    messagingSenderId: '395805938406',
    projectId: 'chat-app-40cea',
    authDomain: 'chat-app-40cea.firebaseapp.com',
    storageBucket: 'chat-app-40cea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsag5R5jMXQQLjrsV1yK4he8KRXfF6sw',
    appId: '1:395805938406:android:108feb4e6f76f97d6d2127',
    messagingSenderId: '395805938406',
    projectId: 'chat-app-40cea',
    storageBucket: 'chat-app-40cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zmI9-veDlPcEYq0z88gIB0BKhA99JMI',
    appId: '1:395805938406:ios:6d3d57cffc8bffeb6d2127',
    messagingSenderId: '395805938406',
    projectId: 'chat-app-40cea',
    storageBucket: 'chat-app-40cea.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zmI9-veDlPcEYq0z88gIB0BKhA99JMI',
    appId: '1:395805938406:ios:6d3d57cffc8bffeb6d2127',
    messagingSenderId: '395805938406',
    projectId: 'chat-app-40cea',
    storageBucket: 'chat-app-40cea.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbxE6calGsvU3XX71hXBx6u7z3m8lYXnQ',
    appId: '1:395805938406:web:d3b0a4b6009913c16d2127',
    messagingSenderId: '395805938406',
    projectId: 'chat-app-40cea',
    authDomain: 'chat-app-40cea.firebaseapp.com',
    storageBucket: 'chat-app-40cea.appspot.com',
  );

}